<?php
/**
* Fivestar Stats module.  This is used for determining voting statistics,
* as well as looking for abuse of the voting system.
*
* @author Douglas Muth <http://www.dmuth.org/>
*/

/**
* Create our menu.
*/
function fivestarstats_menu() {

	$retval = array();

	//
	// Our main menu item.
	//
	$retval["admin/settings/fivestarstats"] = array(
		"title" => "Fivestar Stats",
		"page callback" => "fivestarstats_main",
		"access arguments" => array("administer site configuration"),
		"type" => MENU_NORMAL_ITEM,
		
		);

	return($retval);

} // End of fivestarstats_menu()


/**
* Our permissions function.
* For now, we'll leave this empty.
*/
function fivestarstats_perm() {
	$retval = array();
	return($retval);
}


/**
* Our main function.  It returns the various reports.
*
* @return string The content of the page
*/
function fivestarstats_main() {

	$retval = "";

	$num = 10;

	$data = array();

	include("get_total_stats.inc.php");
	$data["total"] = fivestarstats_get_total_stats();

	include("get_ips.inc.php");
	$data["ips"] = fivestarstats_get_ips($num);

	include("get_user_stats.inc.php");
	$data["users"] = fivestarstats_get_user_stats($num);

$retval .= drupal_get_form("fivestarstats_form", $data);


		//$retval .= "<li>" . l($row["name"], "user/" . $row["uid"]) . ": " 
		//	. t("%num posts", array("%num" => $row["cnt"]))
		//	. "</li>";

	//$retval .= "<h2>Top Posters (nodes and comments)</h2>";
	//$retval .= "<ul>";
	//$retval .= "</ul>";

	$retval .= "<h2>Here's a print_r() of our data. (a real interface is coming soon!)</h2>";

//$retval .= "<pre>" . print_r($data, true) . "</pre>"; // Debugging
$retval .= "<pre>" . print_r($data["ips"], true) . "</pre>"; // Debugging

	return($retval);

} // End of fivestarstats_main()


/**
* Our form callback.
*
* @param array $form_data Form data
*
* @param array $data Our array of data that we passed in
*
* @return array An array of form elements for the form generator.
*/
function fivestarstats_form($form_data, $data) {

	$retval = array();

	$retval["total_votes"] = fivestarstats_form_total_votes($data);

	return($retval);

} // End of fivestarstats_form()


/**
* Create form elements for the total vote data.
*
* @param array $data Our array of data that we passed in
*
* @return array An array of form elements for the form generator.
*/
function fivestarstats_form_total_votes($data) {

	$retval = array();

	$retval = array(
		"#type" => "fieldset",
		"#collapsible" => true,
		"#title" => t("Total Votes"),
		);

	$retval["content"] = array(
		"#type" => "item",
		"#value" => t("%num_votes from %num_ips unique IPs "
			. "with average of %num_stars stars per vote.",
			array("%num_votes" => $data["total"]["num_votes"],
				"%num_ips" => $data["total"]["num_ips"],
				"%num_stars" => $data["total"]["average_stars"])
			)
		);

	return($retval);

} // End of fivestarstats_form_total_values()




